### ISSUE TITLE
errors when units starve and HP sudddenly falls

### ISSUE THREAD

**Issue by andy5995** [KeithSammut/possession_obsession#1]
When HP suddenly drops because of starvation, error messages are produced. There was some other times when I received an error too, not sure why. Might be related to the same issue, or power in the - when magic units are acquired.
![screen4](https://cloud.githubusercontent.com/assets/16764864/15869372/c473e396-2cb1-11e6-869a-bdbdbf022e6f.jpg)
Fun scenario. Thanks.

**Comment by KeithSammut** [comment]
Lmao, just a second ago I got the same thing! Hold on a sec, I think I know the problem, I'll fix it for tommorrow ;) . Thanks for pointing it out bro.
